version: 2
defaults: &defaults
  working_directory: ~/mongoose

jobs:
  test:
    docker:
      - image: circleci/node:8.10
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:8.10
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run compile
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    docker:
      - image: circleci/node:8.10
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
